In [ ]:
from google.colab import files

archivo_subido = files.upload()

Saving Compendios_especialidades_2023.xlsx to Compendios_especialidades_2023.xlsx

In [ ]:
import pandas as pd

ruta_archivo = "Compendios_especialidades_2023.xlsx"

df_original = pd.read_excel(
    ruta_archivo,
    sheet_name="CA_DelitosInf",
    header=None
)

print("Dimensiones originales:", df_original.shape)

display(df_original.iloc[:25, :15])

Dimensiones originales: (104, 186)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,COMPENDIOS POR ESPECIALIDAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Año,Hoja Excel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,CA_DelitosInf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE ANDALUCÍA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,DELITOS INFORMÁTICOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Delitos informáticos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,Almería,Cádiz,Córdoba,Granada,Huelva,Jaén,Málaga,Sevilla,ANDALUCÍA,NaN,NaN,NaN
20,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las ...,Procedimientos judiciales incoados,27,17,0,3,1,257,2,2,309,NaN,NaN,NaN
21,NaN,NaN,Calificaciones,0,4,0,0,0,14,0,2,20,NaN,NaN,NaN
22,NaN,NaN,Sentencias condenatorias,0,0,0,1,0,11,0,2,14,NaN,NaN,NaN
23,NaN,NaN,Diligencias investigación,1,1,1,0,0,0,0,1,4,NaN,NaN,NaN
24,NaN,Acoso cometido a través de las TICs (art 172 ter),Procedimientos judiciales incoados,0,15,NaN,0,0,46,1,7,69,NaN,NaN,NaN

In [ ]:
pd.set_option("display.max_columns", 20)
pd.set_option("display.max_colwidth", 60)

display(df_original.iloc[13:29, 0:13])

,0,1,2,3,4,5,6,7,8,9,10,11,12
13,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE ANDALUCÍA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,DELITOS INFORMÁTICOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Delitos informáticos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,Almería,Cádiz,Córdoba,Granada,Huelva,Jaén,Málaga,Sevilla,ANDALUCÍA,NaN
20,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Procedimientos judiciales incoados,27,17,0,3,1,257,2,2,309,NaN
21,NaN,NaN,Calificaciones,0,4,0,0,0,14,0,2,20,NaN
22,NaN,NaN,Sentencias condenatorias,0,0,0,1,0,11,0,2,14,NaN
23,NaN,NaN,Diligencias investigación,1,1,1,0,0,0,0,1,4,NaN
24,NaN,Acoso cometido a través de las TICs (art 172 ter),Procedimientos judiciales incoados,0,15,NaN,0,0,46,1,7,69,NaN
25,NaN,NaN,Calificaciones,1,4,NaN,0,0,6,1,6,18,NaN
26,NaN,NaN,Sentencias condenatorias,0,3,NaN,0,1,4,1,0,9,NaN
27,NaN,NaN,Diligencias investigación,0,0,NaN,0,0,0,0,2,2,NaN
28,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Procedimientos judiciales incoados,0,0,NaN,0,0,0,NaN,1,1,NaN

In [ ]:
columnas_andalucia = [
    "categoria_delito",
    "tipo_delito",
    "indicador",
    "Almería",
    "Cádiz",
    "Córdoba",
    "Granada",
    "Huelva",
    "Jaén",
    "Málaga",
    "Sevilla",
    "ANDALUCÍA"
]

df_andalucia = df_original.iloc[20:88, 0:12].copy()
df_andalucia.columns = columnas_andalucia

display(df_andalucia.head(12))

,categoria_delito,tipo_delito,indicador,Almería,Cádiz,Córdoba,Granada,Huelva,Jaén,Málaga,Sevilla,ANDALUCÍA
20,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Procedimientos judiciales incoados,27,17,0,3,1,257,2,2,309
21,NaN,NaN,Calificaciones,0,4,0,0,0,14,0,2,20
22,NaN,NaN,Sentencias condenatorias,0,0,0,1,0,11,0,2,14
23,NaN,NaN,Diligencias investigación,1,1,1,0,0,0,0,1,4
24,NaN,Acoso cometido a través de las TICs (art 172 ter),Procedimientos judiciales incoados,0,15,NaN,0,0,46,1,7,69
25,NaN,NaN,Calificaciones,1,4,NaN,0,0,6,1,6,18
26,NaN,NaN,Sentencias condenatorias,0,3,NaN,0,1,4,1,0,9
27,NaN,NaN,Diligencias investigación,0,0,NaN,0,0,0,0,2,2
28,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Procedimientos judiciales incoados,0,0,NaN,0,0,0,NaN,1,1
29,NaN,NaN,Calificaciones,1,8,NaN,0,0,0,NaN,0,9
30,NaN,NaN,Sentencias condenatorias,0,0,NaN,0,0,0,NaN,0,0
31,NaN,NaN,Diligencias investigación,0,0,NaN,0,0,0,NaN,0,0

In [ ]:
df_andalucia[["categoria_delito", "tipo_delito"]] = (
    df_andalucia[["categoria_delito", "tipo_delito"]].ffill()
)

display(df_andalucia.head(12))

,categoria_delito,tipo_delito,indicador,Almería,Cádiz,Córdoba,Granada,Huelva,Jaén,Málaga,Sevilla,ANDALUCÍA
20,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Procedimientos judiciales incoados,27,17,0,3,1,257,2,2,309
21,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Calificaciones,0,4,0,0,0,14,0,2,20
22,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Sentencias condenatorias,0,0,0,1,0,11,0,2,14
23,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Diligencias investigación,1,1,1,0,0,0,0,1,4
24,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Procedimientos judiciales incoados,0,15,NaN,0,0,46,1,7,69
25,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Calificaciones,1,4,NaN,0,0,6,1,6,18
26,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Sentencias condenatorias,0,3,NaN,0,1,4,1,0,9
27,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Diligencias investigación,0,0,NaN,0,0,0,0,2,2
28,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Procedimientos judiciales incoados,0,0,NaN,0,0,0,NaN,1,1
29,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Calificaciones,1,8,NaN,0,0,0,NaN,0,9
30,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Sentencias condenatorias,0,0,NaN,0,0,0,NaN,0,0
31,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Diligencias investigación,0,0,NaN,0,0,0,NaN,0,0

In [ ]:
df_andalucia_largo = df_andalucia.melt(
    id_vars=[
        "categoria_delito",
        "tipo_delito",
        "indicador"
    ],
    var_name="territorio",
    value_name="valor"
)

print("Dimensiones:", df_andalucia_largo.shape)

display(df_andalucia_largo.head(15))

Dimensiones: (612, 5)

,categoria_delito,tipo_delito,indicador,territorio,valor
0,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Procedimientos judiciales incoados,Almería,27
1,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Calificaciones,Almería,0
2,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Sentencias condenatorias,Almería,0
3,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Diligencias investigación,Almería,1
4,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Procedimientos judiciales incoados,Almería,0
5,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Calificaciones,Almería,1
6,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Sentencias condenatorias,Almería,0
7,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Diligencias investigación,Almería,0
8,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Procedimientos judiciales incoados,Almería,0
9,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Calificaciones,Almería,1
10,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Sentencias condenatorias,Almería,0
11,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Diligencias investigación,Almería,0
12,Delitos contra la libertad sexual,Delitos de pornografía infantil o personas con discapaci...,Procedimientos judiciales incoados,Almería,16
13,Delitos contra la libertad sexual,Delitos de pornografía infantil o personas con discapaci...,Calificaciones,Almería,11
14,Delitos contra la libertad sexual,Delitos de pornografía infantil o personas con discapaci...,Sentencias condenatorias,Almería,7

In [ ]:
df_andalucia_largo["anio"] = 2023
df_andalucia_largo["comunidad_autonoma"] = "Andalucía"
df_andalucia_largo["nivel_territorial"] = "provincia"

df_andalucia_largo.loc[
    df_andalucia_largo["territorio"] == "ANDALUCÍA",
    "nivel_territorial"
] = "comunidad_autonoma"

df_andalucia_largo = df_andalucia_largo[
    [
        "anio",
        "comunidad_autonoma",
        "nivel_territorial",
        "territorio",
        "categoria_delito",
        "tipo_delito",
        "indicador",
        "valor"
    ]
]

display(
    pd.concat([
        df_andalucia_largo.head(3),
        df_andalucia_largo.tail(3)
    ])
)

,anio,comunidad_autonoma,nivel_territorial,territorio,categoria_delito,tipo_delito,indicador,valor
0,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Procedimientos judiciales incoados,27
1,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Calificaciones,0
2,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Sentencias condenatorias,0
609,2023,Andalucía,comunidad_autonoma,ANDALUCÍA,Delitos contra la constitución,Delitos de discriminación cometidos a través de las TICs...,Calificaciones,2
610,2023,Andalucía,comunidad_autonoma,ANDALUCÍA,Delitos contra la constitución,Delitos de discriminación cometidos a través de las TICs...,Sentencias condenatorias,1
611,2023,Andalucía,comunidad_autonoma,ANDALUCÍA,Delitos contra la constitución,Delitos de discriminación cometidos a través de las TICs...,Diligencias investigación,1

In [ ]:
print("Valores nulos por columna:")

display(
    df_andalucia_largo
    .isna()
    .sum()
    .to_frame(name="cantidad_nulos")
)

print("Tipos de datos:")

display(
    df_andalucia_largo
    .dtypes
    .to_frame(name="tipo_dato")
)

Valores nulos por columna:

                    cantidad_nulos
anio                             0
comunidad_autonoma               0
nivel_territorial                0
territorio                       0
categoria_delito                 0
tipo_delito                      0
indicador                        0
valor                          116

Tipos de datos:

                   tipo_dato
anio                   int64
comunidad_autonoma    object
nivel_territorial     object
territorio            object
categoria_delito      object
tipo_delito           object
indicador             object
valor                 object

In [ ]:
nulos_por_territorio = (
    df_andalucia_largo[
        df_andalucia_largo["valor"].isna()
    ]
    .groupby("territorio")
    .size()
    .reset_index(name="cantidad_nulos")
)

display(nulos_por_territorio)

  territorio  cantidad_nulos
0    Córdoba              44
1     Huelva              32
2     Málaga              40

In [ ]:
df_andalucia_largo["valor"] = (
    df_andalucia_largo["valor"].astype("Int64")
)

print("Tipo de dato de valor:", df_andalucia_largo["valor"].dtype)
print("Valores nulos conservados:", df_andalucia_largo["valor"].isna().sum())

display(
    df_andalucia_largo.loc[
        df_andalucia_largo["valor"].isna(),
        ["territorio", "tipo_delito", "indicador", "valor"]
    ].head(8)
)

Tipo de dato de valor: Int64
Valores nulos conservados: 116

,territorio,tipo_delito,indicador,valor
140,Córdoba,Acoso cometido a través de las TICs (art 172 ter),Procedimientos judiciales incoados,<NA>
141,Córdoba,Acoso cometido a través de las TICs (art 172 ter),Calificaciones,<NA>
142,Córdoba,Acoso cometido a través de las TICs (art 172 ter),Sentencias condenatorias,<NA>
143,Córdoba,Acoso cometido a través de las TICs (art 172 ter),Diligencias investigación,<NA>
144,Córdoba,Trato degradante cometido a través de las TICs (art 173),Procedimientos judiciales incoados,<NA>
145,Córdoba,Trato degradante cometido a través de las TICs (art 173),Calificaciones,<NA>
146,Córdoba,Trato degradante cometido a través de las TICs (art 173),Sentencias condenatorias,<NA>
147,Córdoba,Trato degradante cometido a través de las TICs (art 173),Diligencias investigación,<NA>

In [ ]:
claves = [
    "categoria_delito",
    "tipo_delito",
    "indicador"
]

suma_provincias = (
    df_andalucia_largo[
        df_andalucia_largo["nivel_territorial"] == "provincia"
    ]
    .groupby(claves, as_index=False)["valor"]
    .sum(min_count=1)
    .rename(columns={"valor": "suma_provincias"})
)

totales_andalucia = (
    df_andalucia_largo[
        df_andalucia_largo["nivel_territorial"] == "comunidad_autonoma"
    ][claves + ["valor"]]
    .rename(columns={"valor": "total_andalucia"})
)

control_totales = suma_provincias.merge(
    totales_andalucia,
    on=claves,
    how="outer",
    validate="one_to_one"
)

control_totales["diferencia"] = (
    control_totales["suma_provincias"]
    - control_totales["total_andalucia"]
)

display(
    control_totales["diferencia"]
    .value_counts(dropna=False)
    .rename_axis("diferencia")
    .reset_index(name="cantidad")
)

   diferencia  cantidad
0           0        68

In [ ]:
inicios_bloques = [
    numero_columna
    for numero_columna, contenido in enumerate(df_original.iloc[13])
    if isinstance(contenido, str)
    and contenido.strip().upper().startswith("FISCAL")
]

bloques_detectados = pd.DataFrame({
    "columna_inicio": inicios_bloques,
    "encabezado_original": [
        df_original.iloc[13, columna].strip()
        for columna in inicios_bloques
    ]
})

print("Comunidades autónomas detectadas:", len(bloques_detectados))

display(bloques_detectados)

Comunidades autónomas detectadas: 17

,columna_inicio,encabezado_original
0,0,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE ANDALUCÍA
1,15,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE ARAGÓN
2,25,FISCALÍA DE LA COMUNIDAD AUTÓNOMA DEL PRINCIPADO DE ASTU...
3,32,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE BALEARES
4,39,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE CANARIAS
5,47,FISCALÍA DE LA COMUNIDAD AUTÓNOMA DE CANTABRIA
6,54,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE CASTILLA-LA MANCHA
7,65,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE CASTILLA Y LEÓN
8,81,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE CATALUÑA
9,92,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE EXTREMADURA
10,101,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE GALICIA
11,112,FISCALÍA DE LA COMUNIDAD AUTÓNOMA DE LA RIOJA
12,119,FISCALÍA DE LA COMUNIDAD AUTÓNOMA DE MADRID
13,126,FISCALÍA DE LA COMUNIDAD AUTÓNOMA DE LA REGIÓN DE MURCIA
14,133,FISCALÍA DE LA COMUNIDAD AUTÓNOMA DE NAVARRA
15,140,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DEL PAÍS VASCO
16,150,FISCALÍAS DE LA COMUNIDAD AUTÓNOMA DE VALENCIA

In [ ]:
columna_total_nacional = next(
    numero_columna
    for numero_columna, contenido in enumerate(df_original.iloc[13])
    if isinstance(contenido, str)
    and contenido.strip().upper() == "TOTAL NIVEL NACIONAL"
)

limites_bloques = (
    inicios_bloques[1:]
    + [columna_total_nacional]
)

resumen_bloques = []

for inicio, limite in zip(inicios_bloques, limites_bloques):
    territorios = [
        contenido.strip()
        for contenido in df_original.iloc[19, inicio:limite]
        if isinstance(contenido, str)
        and contenido.strip()
    ]

    resumen_bloques.append({
        "columna_inicio": inicio,
        "numero_territorios": len(territorios),
        "territorios_detectados": territorios,
        "total_comunidad": territorios[-1]
    })

df_resumen_bloques = pd.DataFrame(resumen_bloques)

display(df_resumen_bloques)

,columna_inicio,numero_territorios,territorios_detectados,total_comunidad
0,0,9,"[Almería, Cádiz, Córdoba, Granada, Huelva, Jaén, Málaga,...",ANDALUCÍA
1,15,4,"[Huesca, Teruel, Zaragoza, ARAGÓN]",ARAGÓN
2,25,1,[ASTURIAS],ASTURIAS
3,32,1,[BALEARES],BALEARES
4,39,3,"[Las Palmas, Santa Cruz De Tenerife, CANARIAS]",CANARIAS
5,47,1,[CANTABRIA],CANTABRIA
6,54,6,"[Albacete, Ciudad Real, Cuenca, Guadalajara, Toledo, CAS...",CASTILLA-LA MANCHA
7,65,10,"[Burgos, León, Palencia, Salamanca, Segovia, Soria, Vall...",CASTILLA Y LEÓN
8,81,5,"[Barcelona, Girona, Lleida, Tarragona, CATALUÑA]",CATALUÑA
9,92,3,"[Badajoz, Cáceres, EXTREMADURA]",EXTREMADURA
10,101,5,"[A Coruña, Lugo, Ourense, Pontevedra, GALICIA]",GALICIA
11,112,1,[LA RIOJA],LA RIOJA
12,119,1,[MADRID],MADRID
13,126,1,[MURCIA],MURCIA
14,133,1,[NAVARRA],NAVARRA
15,140,4,"[Araba/Álava, Bizkaia, Gipuzkoa, PAÍS VASCO]",PAÍS VASCO
16,150,4,"[Alicante, Castellón, Valencia, COMUNIDAD VALENCIANA]",COMUNIDAD VALENCIANA

In [ ]:
bloques_largos = []

for inicio, limite in zip(inicios_bloques, limites_bloques):

    columnas_territorio = [
        columna
        for columna in range(inicio + 3, limite)
        if isinstance(df_original.iloc[19, columna], str)
        and df_original.iloc[19, columna].strip()
    ]

    territorios = [
        df_original.iloc[19, columna].strip()
        for columna in columnas_territorio
    ]

    columnas_bloque = [
        inicio,
        inicio + 1,
        inicio + 2
    ] + columnas_territorio

    df_bloque = df_original.iloc[
        20:88,
        columnas_bloque
    ].copy()

    df_bloque.columns = [
        "categoria_delito",
        "tipo_delito",
        "indicador"
    ] + territorios

    df_bloque[
        ["categoria_delito", "tipo_delito"]
    ] = df_bloque[
        ["categoria_delito", "tipo_delito"]
    ].ffill()

    df_bloque_largo = df_bloque.melt(
        id_vars=[
            "categoria_delito",
            "tipo_delito",
            "indicador"
        ],
        var_name="territorio",
        value_name="valor"
    )

    total_comunidad = territorios[-1]

    nombre_comunidad = (
        total_comunidad
        .title()
        .replace(" Y ", " y ")
    )

    df_bloque_largo["anio"] = 2023
    df_bloque_largo["comunidad_autonoma"] = nombre_comunidad
    df_bloque_largo["nivel_territorial"] = "provincia"

    es_total_comunidad = (
        df_bloque_largo["territorio"] == total_comunidad
    )

    df_bloque_largo.loc[
        es_total_comunidad,
        "nivel_territorial"
    ] = "comunidad_autonoma"

    df_bloque_largo.loc[
        es_total_comunidad,
        "territorio"
    ] = nombre_comunidad

    bloques_largos.append(
        df_bloque_largo[
            [
                "anio",
                "comunidad_autonoma",
                "nivel_territorial",
                "territorio",
                "categoria_delito",
                "tipo_delito",
                "indicador",
                "valor"
            ]
        ]
    )

df_delitos_espana = pd.concat(
    bloques_largos,
    ignore_index=True
)

df_delitos_espana["valor"] = (
    df_delitos_espana["valor"].astype("Int64")
)

print("Dimensiones:", df_delitos_espana.shape)
print(
    "Comunidades autónomas:",
    df_delitos_espana["comunidad_autonoma"].nunique()
)

display(df_delitos_espana.head(10))

Dimensiones: (4080, 8)
Comunidades autónomas: 17

,anio,comunidad_autonoma,nivel_territorial,territorio,categoria_delito,tipo_delito,indicador,valor
0,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Procedimientos judiciales incoados,27
1,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Calificaciones,0
2,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Sentencias condenatorias,0
3,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Amenazas/coacciones cometidos a través de las TICs (art ...,Diligencias investigación,1
4,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Procedimientos judiciales incoados,0
5,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Calificaciones,1
6,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Sentencias condenatorias,0
7,2023,Andalucía,provincia,Almería,Delitos contra la libertad,Acoso cometido a través de las TICs (art 172 ter),Diligencias investigación,0
8,2023,Andalucía,provincia,Almería,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Procedimientos judiciales incoados,0
9,2023,Andalucía,provincia,Almería,Delitos contra la integridad moral,Trato degradante cometido a través de las TICs (art 173),Calificaciones,1

In [ ]:
df_total_nacional = df_original.iloc[
    20:88,
    [159, 160, 161, 162]
].copy()

df_total_nacional.columns = [
    "categoria_delito",
    "tipo_delito",
    "indicador",
    "valor"
]

df_total_nacional[
    ["categoria_delito", "tipo_delito"]
] = df_total_nacional[
    ["categoria_delito", "tipo_delito"]
].ffill()

df_total_nacional["anio"] = 2023
df_total_nacional["comunidad_autonoma"] = pd.NA
df_total_nacional["nivel_territorial"] = "nacional"
df_total_nacional["territorio"] = "España"

df_total_nacional["valor"] = (
    df_total_nacional["valor"].astype("Int64")
)

df_total_nacional = df_total_nacional[
    [
        "anio",
        "comunidad_autonoma",
        "nivel_territorial",
        "territorio",
        "categoria_delito",
        "tipo_delito",
        "indicador",
        "valor"
    ]
]

df_delitos_completo = pd.concat(
    [
        df_delitos_espana,
        df_total_nacional
    ],
    ignore_index=True
)

print("Dimensiones finales:", df_delitos_completo.shape)

display(
    df_delitos_completo["nivel_territorial"]
    .value_counts()
    .rename_axis("nivel_territorial")
    .reset_index(name="cantidad_filas")
)

Dimensiones finales: (4148, 8)

    nivel_territorial  cantidad_filas
0           provincia            2924
1  comunidad_autonoma            1156
2            nacional              68

In [ ]:
claves_nacionales = [
    "categoria_delito",
    "tipo_delito",
    "indicador"
]

suma_comunidades = (
    df_delitos_completo[
        df_delitos_completo["nivel_territorial"]
        == "comunidad_autonoma"
    ]
    .groupby(claves_nacionales, as_index=False)["valor"]
    .sum(min_count=1)
    .rename(columns={"valor": "suma_comunidades"})
)

totales_nacionales = (
    df_delitos_completo[
        df_delitos_completo["nivel_territorial"]
        == "nacional"
    ][claves_nacionales + ["valor"]]
    .rename(columns={"valor": "total_nacional"})
)

control_nacional = suma_comunidades.merge(
    totales_nacionales,
    on=claves_nacionales,
    how="outer",
    validate="one_to_one"
)

control_nacional["diferencia"] = (
    control_nacional["suma_comunidades"]
    - control_nacional["total_nacional"]
)

display(
    control_nacional["diferencia"]
    .value_counts(dropna=False)
    .rename_axis("diferencia")
    .reset_index(name="cantidad")
)

   diferencia  cantidad
0           0        68

In [ ]:
claves_autonomicas = [
    "comunidad_autonoma",
    "categoria_delito",
    "tipo_delito",
    "indicador"
]

suma_provincias = (
    df_delitos_completo[
        df_delitos_completo["nivel_territorial"]
        == "provincia"
    ]
    .groupby(claves_autonomicas, as_index=False)["valor"]
    .sum(min_count=1)
    .rename(columns={"valor": "suma_provincias"})
)

totales_comunidades = (
    df_delitos_completo[
        df_delitos_completo["nivel_territorial"]
        == "comunidad_autonoma"
    ][claves_autonomicas + ["valor"]]
    .rename(columns={"valor": "total_comunidad"})
)

control_autonomico = suma_provincias.merge(
    totales_comunidades,
    on=claves_autonomicas,
    how="left",
    validate="one_to_one"
)

control_autonomico["diferencia"] = (
    control_autonomico["suma_provincias"]
    - control_autonomico["total_comunidad"]
)

print(
    "Comunidades comprobadas:",
    control_autonomico["comunidad_autonoma"].nunique()
)

display(
    control_autonomico["diferencia"]
    .value_counts(dropna=False)
    .rename_axis("diferencia")
    .reset_index(name="cantidad")
)

Comunidades comprobadas: 10

   diferencia  cantidad
0           0       680

In [ ]:
claves_registro = [
    "anio",
    "nivel_territorial",
    "territorio",
    "categoria_delito",
    "tipo_delito",
    "indicador"
]

resumen_calidad = pd.DataFrame({
    "control": [
        "Filas totales",
        "Registros duplicados",
        "Valores nulos en valor",
        "Valores negativos",
        "Filas nacionales sin comunidad autónoma",
        "Categorías de delito",
        "Tipos de delito",
        "Indicadores"
    ],
    "resultado": [
        len(df_delitos_completo),
        df_delitos_completo.duplicated(
            subset=claves_registro
        ).sum(),
        df_delitos_completo["valor"].isna().sum(),
        df_delitos_completo["valor"].lt(0).sum(),
        (
            (
                df_delitos_completo["nivel_territorial"]
                == "nacional"
            )
            & (
                df_delitos_completo["comunidad_autonoma"]
                .isna()
            )
        ).sum(),
        df_delitos_completo["categoria_delito"].nunique(),
        df_delitos_completo["tipo_delito"].nunique(),
        df_delitos_completo["indicador"].nunique()
    ]
})

display(resumen_calidad)

                                   control  resultado
0                            Filas totales       4148
1                     Registros duplicados          0
2                   Valores nulos en valor        763
3                        Valores negativos          0
4  Filas nacionales sin comunidad autónoma         68
5                     Categorías de delito          8
6                          Tipos de delito         17
7                              Indicadores          4

In [ ]:
df_final = df_delitos_completo.copy()

columnas_texto = [
    "comunidad_autonoma",
    "nivel_territorial",
    "territorio",
    "categoria_delito",
    "tipo_delito",
    "indicador"
]

for columna in columnas_texto:
    df_final[columna] = (
        df_final[columna]
        .astype("string")
        .str.strip()
    )

df_final["anio"] = df_final["anio"].astype("Int64")
df_final["valor"] = df_final["valor"].astype("Int64")

nombre_csv = "delitos_informaticos_2023_limpio.csv"

df_final.to_csv(
    nombre_csv,
    index=False,
    encoding="utf-8",
    na_rep=""
)

print("Archivo creado:", nombre_csv)
print("Filas exportadas:", len(df_final))

files.download(nombre_csv)

Archivo creado: delitos_informaticos_2023_limpio.csv
Filas exportadas: 4148

In [21]:
from google.colab import auth

auth.authenticate_user()

print("Autenticación completada.")

Autenticación completada.

In [22]:
from google.cloud import bigquery

project_id = "cool-framing-412121"
dataset_id = "delitos_informaticos"

cliente_bigquery = bigquery.Client(
    project=project_id,
    location="EU"
)

dataset = cliente_bigquery.get_dataset(
    f"{project_id}.{dataset_id}"
)

print("Conexión con BigQuery correcta.")
print("Dataset:", dataset.full_dataset_id)
print("Ubicación:", dataset.location)

Conexión con BigQuery correcta.
Dataset: cool-framing-412121:delitos_informaticos
Ubicación: EU

In [23]:
table_id = (
    "cool-framing-412121."
    "delitos_informaticos."
    "delitos_informaticos_2023"
)

esquema = [
    bigquery.SchemaField("anio", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField(
        "comunidad_autonoma",
        "STRING",
        mode="NULLABLE"
    ),
    bigquery.SchemaField(
        "nivel_territorial",
        "STRING",
        mode="REQUIRED"
    ),
    bigquery.SchemaField(
        "territorio",
        "STRING",
        mode="REQUIRED"
    ),
    bigquery.SchemaField(
        "categoria_delito",
        "STRING",
        mode="REQUIRED"
    ),
    bigquery.SchemaField(
        "tipo_delito",
        "STRING",
        mode="REQUIRED"
    ),
    bigquery.SchemaField(
        "indicador",
        "STRING",
        mode="REQUIRED"
    ),
    bigquery.SchemaField(
        "valor",
        "INTEGER",
        mode="NULLABLE"
    )
]

configuracion_carga = bigquery.LoadJobConfig(
    schema=esquema,
    create_disposition=(
        bigquery.CreateDisposition.CREATE_IF_NEEDED
    ),
    write_disposition=(
        bigquery.WriteDisposition.WRITE_EMPTY
    )
)

trabajo_carga = cliente_bigquery.load_table_from_dataframe(
    df_final,
    table_id,
    job_config=configuracion_carga,
    location="EU"
)

trabajo_carga.result()

tabla = cliente_bigquery.get_table(table_id)

print("Tabla cargada correctamente.")
print("Tabla:", tabla.full_table_id)
print("Filas:", tabla.num_rows)
print("Columnas:", len(tabla.schema))

Tabla cargada correctamente.
Tabla: cool-framing-412121:delitos_informaticos.delitos_informaticos_2023
Filas: 4148
Columnas: 8

In [25]:
consulta_validacion = """
SELECT
    nivel_territorial,
    COUNT(*) AS cantidad_filas,
    COUNT(valor) AS valores_informados,
    COUNTIF(valor IS NULL) AS valores_nulos
FROM
    `cool-framing-412121.delitos_informaticos.delitos_informaticos_2023`
GROUP BY
    nivel_territorial
ORDER BY
    CASE nivel_territorial
        WHEN 'provincia' THEN 1
        WHEN 'comunidad_autonoma' THEN 2
        WHEN 'nacional' THEN 3
    END
"""

configuracion_consulta = bigquery.QueryJobConfig(
    maximum_bytes_billed=10_485_760
)

resultado_validacion = cliente_bigquery.query(
    consulta_validacion,
    job_config=configuracion_consulta,
    location="EU"
).to_dataframe()

display(resultado_validacion)

    nivel_territorial  cantidad_filas  valores_informados  valores_nulos
0           provincia            2924                2287            637
1  comunidad_autonoma            1156                1030            126
2            nacional              68                  68              0